### ISSUE TITLE
502 Bad Gateway with 113: Host is unreachable

### ISSUE THREAD

**Issue by gjb25638** [nevadskiy/laravel-nuxt-docker#16]
Hi @nevadskiy 

I inspired a lot from your docker architecture design.

When I try to use to build after I add some code to nuxt boilerplate,
nuxt part could run fine and see result on browser after set up,
but I always encountered '502 Bad Gateway' problem after a while.

I trace error from Nginx error.log file,
and get error message with 'connect() failed (113: Host is unreachable)'.
I try to add 'resolver client valid=30s ipv6=off;' in Nginx default.conf setting but it didn't help.

Could you have some advise?
Thanks.

**Comment by cosminproca** [comment]
@gjb25638 I have encountered this issue as well, I think you should check that the client container is working properly. 
I noticed that even if it built correctly after running `docker-compose ps` my client was actually not running because of a nuxt error post build (I put some wrong configuration settings)

**Comment by xalaida** [comment]
@gjb25638 @hotbooster9858 yes, the issue is real, if nuxt configuration is broken and the app cannot be built. 
For now, I can recommend using `docker-compose restart client` command when you see the error.
Probably it can be also resolved using `restart: always` configuration option for client service in the `docker-compose.yml` file.

**Comment by xalaida** [comment]
@gjb25638 Try to check what is the problem with nuxt using `docker-compose logs client` command, fix it and restart the container. Then it should be fine.

**Comment by gjb25638** [comment]
Hi @nevadskiy, @hotbooster9858

Thank you so much for give some very useful advice.
I'am so grateful.

Yes you are right,
the problem is occur from client container.

when I using `docker-compose logs client`,
I see the error message,
and I can't solve this problem temporarily,
so I follow your suggestion,
using `restart: always` config setting for client side in the `docker-compose.yml`,
and solve this headache issue for me.

Thank you very much.
